# Generated by YCM Generator at 2019-06-17 11:05:34.446723

# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os
import ycm_core

flags = [
    '-x',
    'c++',
    '-DBOOST_TEST_DYN_LINK',
    '-DBUILD_KIWAY_DLL',
    '-DCOMPILE_SGLIB',
    '-DCOMPILING_DLL',
    '-DCVPCB',
    '-DEESCHEMA',
    '-DGERBVIEW',
    '-DGLM_FORCE_CTOR_INIT',
    '-DHAVE_STDINT_H',
    '-DKICAD',
    '-DKICAD_CONFIG_DIR=kicad',
    '-DKICAD_SCRIPTING',
    '-DKICAD_SCRIPTING_ACTION_MENU',
    '-DKICAD_SCRIPTING_MODULES',
    '-DKICAD_SCRIPTING_WXPYTHON',
    '-DKICAD_SPICE',
    '-DKICAD_USE_OCE',
    '-DNDEBUG',
    '-DNGSPICE_DLL_FILE="libngspice.so.0.0.0"',
    '-DPCBNEW',
    '-DPGM_DATA_FILE_EXT="kicad_pcb"',
    '-DPL_EDITOR',
    '-DQA_EESCHEMA_DATA_LOCATION=("/home/johannes/build/kicad/qa/eeschema/data")',
    '-DTOP_FRAME=FRAME_BM2CMP',
    '-DUSE_TOOL_MANAGER',
    '-DUSE_WX_OVERLAY',
    '-DWXUSINGDLL',
    '-DWX_COMPATIBILITY',
    '-D_FILE_OFFSET_BITS=64',
    '-D__WXGTK__',
    '-Dcvpcb_kiface_EXPORTS',
    '-Deeschema_kiface_EXPORTS',
    '-Dgerbview_kiface_EXPORTS',
    '-Dkicad_3dsg_EXPORTS',
    '-Dpcb_calculator_kiface_EXPORTS',
    '-Dpl_editor_kiface_EXPORTS',
    '-Ds3d_plugin_idf_EXPORTS',
    '-Ds3d_plugin_oce_EXPORTS',
    '-Ds3d_plugin_vrml_EXPORTS',
    '-I/home/johannes/build/kicad',
    '-I/home/johannes/build/kicad/3d-viewer',
    '-I/home/johannes/build/kicad/3d-viewer/.',
    '-I/home/johannes/build/kicad/3d-viewer/../pcbnew',
    '-I/home/johannes/build/kicad/3d-viewer/3d_cache',
    '-I/home/johannes/build/kicad/3d-viewer/3d_canvas',
    '-I/home/johannes/build/kicad/3d-viewer/3d_rendering',
    '-I/home/johannes/build/kicad/3d-viewer/3d_viewer',
    '-I/home/johannes/build/kicad/bitmap2component/.',
    '-I/home/johannes/build/kicad/bitmap2component/../potrace',
    '-I/home/johannes/build/kicad/bitmaps_png/include',
    '-I/home/johannes/build/kicad/common',
    '-I/home/johannes/build/kicad/common/.',
    '-I/home/johannes/build/kicad/common/../3d-viewer',
    '-I/home/johannes/build/kicad/common/../include/legacy_gal',
    '-I/home/johannes/build/kicad/common/../pcbnew',
    '-I/home/johannes/build/kicad/common/./dialog_about',
    '-I/home/johannes/build/kicad/common/./dialogs',
    '-I/home/johannes/build/kicad/common/./widgets',
    '-I/home/johannes/build/kicad/common/geometry',
    '-I/home/johannes/build/kicad/cvpcb/.',
    '-I/home/johannes/build/kicad/cvpcb/../3d-viewer',
    '-I/home/johannes/build/kicad/cvpcb/../common',
    '-I/home/johannes/build/kicad/cvpcb/../pcbnew',
    '-I/home/johannes/build/kicad/cvpcb/../pcbnew/dialogs',
    '-I/home/johannes/build/kicad/cvpcb/./dialogs',
    '-I/home/johannes/build/kicad/dxflib_qcad',
    '-I/home/johannes/build/kicad/eeschema',
    '-I/home/johannes/build/kicad/eeschema/.',
    '-I/home/johannes/build/kicad/eeschema/../common',
    '-I/home/johannes/build/kicad/eeschema/../common/dialogs',
    '-I/home/johannes/build/kicad/eeschema/./dialogs',
    '-I/home/johannes/build/kicad/eeschema/./libedit',
    '-I/home/johannes/build/kicad/eeschema/./libview',
    '-I/home/johannes/build/kicad/eeschema/./netlist_exporters',
    '-I/home/johannes/build/kicad/eeschema/./tools',
    '-I/home/johannes/build/kicad/eeschema/./widgets',
    '-I/home/johannes/build/kicad/gerbview/.',
    '-I/home/johannes/build/kicad/gerbview/../3d-viewer',
    '-I/home/johannes/build/kicad/gerbview/../common',
    '-I/home/johannes/build/kicad/gerbview/../pcbnew',
    '-I/home/johannes/build/kicad/gerbview/dialogs',
    '-I/home/johannes/build/kicad/include',
    '-I/home/johannes/build/kicad/include/gal/opengl',
    '-I/home/johannes/build/kicad/kicad/.',
    '-I/home/johannes/build/kicad/kicad/../eeschema',
    '-I/home/johannes/build/kicad/kicad/../pcbnew',
    '-I/home/johannes/build/kicad/libs/sexpr/include',
    '-I/home/johannes/build/kicad/pagelayout_editor/.',
    '-I/home/johannes/build/kicad/pagelayout_editor/../common/dialogs',
    '-I/home/johannes/build/kicad/pagelayout_editor/dialogs',
    '-I/home/johannes/build/kicad/pcb_calculator/.',
    '-I/home/johannes/build/kicad/pcb_calculator/../common',
    '-I/home/johannes/build/kicad/pcb_calculator/attenuators',
    '-I/home/johannes/build/kicad/pcb_calculator/bitmaps',
    '-I/home/johannes/build/kicad/pcb_calculator/dialogs',
    '-I/home/johannes/build/kicad/pcb_calculator/transline',
    '-I/home/johannes/build/kicad/pcbnew',
    '-I/home/johannes/build/kicad/pcbnew/.',
    '-I/home/johannes/build/kicad/pcbnew/../3d-viewer',
    '-I/home/johannes/build/kicad/pcbnew/../common',
    '-I/home/johannes/build/kicad/pcbnew/../common/dialogs',
    '-I/home/johannes/build/kicad/pcbnew/../common/swig',
    '-I/home/johannes/build/kicad/pcbnew/../dxflib_qcad',
    '-I/home/johannes/build/kicad/pcbnew/../utils/idftools',
    '-I/home/johannes/build/kicad/pcbnew/./autorouter',
    '-I/home/johannes/build/kicad/pcbnew/./dialogs',
    '-I/home/johannes/build/kicad/pcbnew/./exporters',
    '-I/home/johannes/build/kicad/pcbnew/./specctra_import_export',
    '-I/home/johannes/build/kicad/pcbnew/connectivity/.',
    '-I/home/johannes/build/kicad/pcbnew/connectivity/..',
    '-I/home/johannes/build/kicad/pcbnew/connectivity/../../include',
    '-I/home/johannes/build/kicad/pcbnew/dialogs',
    '-I/home/johannes/build/kicad/pcbnew/github/.',
    '-I/home/johannes/build/kicad/pcbnew/pcad2kicadpcb_plugin/.',
    '-I/home/johannes/build/kicad/pcbnew/router',
    '-I/home/johannes/build/kicad/pcbnew/router/.',
    '-I/home/johannes/build/kicad/pcbnew/router/..',
    '-I/home/johannes/build/kicad/pcbnew/router/../../3d-viewer',
    '-I/home/johannes/build/kicad/pcbnew/router/../../include',
    '-I/home/johannes/build/kicad/pcbnew/router/../../pcbnew',
    '-I/home/johannes/build/kicad/pcbnew/swig',
    '-I/home/johannes/build/kicad/pcbnew/tools',
    '-I/home/johannes/build/kicad/plugins/3d/idf',
    '-I/home/johannes/build/kicad/plugins/3d/vrml',
    '-I/home/johannes/build/kicad/plugins/3d/vrml/v1',
    '-I/home/johannes/build/kicad/plugins/3d/vrml/v2',
    '-I/home/johannes/build/kicad/plugins/3d/vrml/x3d',
    '-I/home/johannes/build/kicad/polygon',
    '-I/home/johannes/build/kicad/polygon/.',
    '-I/home/johannes/build/kicad/polygon/include',
    '-I/home/johannes/build/kicad/potrace/.',
    '-I/home/johannes/build/kicad/qa/eeschema/.',
    '-I/home/johannes/build/kicad/qa/gal/gal_pixel_alignment/.',
    '-I/home/johannes/build/kicad/qa/libs/sexpr',
    '-I/home/johannes/build/kicad/qa/pcbnew_utils/.',
    '-I/home/johannes/build/kicad/qa/pcbnew_utils/BEFORE',
    '-I/home/johannes/build/kicad/qa/pcbnew_utils/include',
    '-I/home/johannes/build/kicad/qa/qa_utils',
    '-I/home/johannes/build/kicad/qa/qa_utils/.',
    '-I/home/johannes/build/kicad/qa/qa_utils/include',
    '-I/home/johannes/build/kicad/qa/unit_test_utils/include',
    '-I/home/johannes/build/kicad/qa/utils/kicad2step',
    '-I/home/johannes/build/kicad/scripting',
    '-I/home/johannes/build/kicad/utils/idftools',
    '-I/home/johannes/build/kicad/utils/kicad-ogltest',
    '-I/home/johannes/build/kicad/utils/kicad-ogltest/../../common',
    '-I/home/johannes/build/kicad/utils/kicad-ogltest/../../include',
    '-I/home/johannes/build/kicad/utils/kicad2step',
    '-I/tmp/tmpOkkbVb',
    '-I/tmp/tmpOkkbVb/3d-viewer',
    '-I/usr/include/cairo',
    '-I/usr/include/pixman-1',
    '-I/usr/include/python2.7',
    '-I/usr/include/x86_64-linux-gnu',
    '-I/usr/lib/x86_64-linux-gnu/oce-0.17/../../../include/oce',
    '-I/usr/local/include/soci',
    '-I/usr/local/share/ngspice/include',
    '-Wall',
    '-Werror=vla',
    '-Wshadow',
    '-std=gnu++11',
    '-isystem', '/usr/include/wx-3.0',
    '-isystem', '/usr/lib/x86_64-linux-gnu/oce-0.17/../../../include/oce',
    '-isystem', '/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0',
]


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.C', '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.H', '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )

  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }

